.TH SIPI\-CLI 1 "2026-08-11" "SiPi 41.24.0" "SiPi User Manual"
.SH NAME
sipi\-cli \- interfaz de linea de comandos profesional para proyectos SiPi
.SH SYNOPSIS
.B sipi-cli
\fICOMANDO\fR [\fIARGUMENTOS\fR...]
.SH DESCRIPTION
.B sipi\-cli
es la herramienta de linea de comandos pensada para trabajar con
proyectos SiPi de forma parecida a otras herramientas de linea de
comandos de lenguajes modernos: crear proyectos, correr la bateria de
tests de regresion, y demas tareas de mantenimiento de un proyecto
SiPi, por afuera de la ejecucion de un solo archivo (para eso esta
.BR sipi (1)).
.SH OPTIONS
Correr
.B sipi-cli --help
muestra la lista completa y actualizada de subcomandos disponibles en
esta version.
.SH SEE ALSO
.BR sipi (1),
.BR sipi\-editor (1)
.SH AUTHOR
Mateo \(em NovaLab Corporation.
